server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: boot_host
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          max-attempts: 5
          initial-interval: 7000
          enabled: true

